---
title: "RMarkdown HW"
author: "Emre Demirhan"
date: "17 10 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

**Who is Emre Demirhan?**

I graduated from departmant of Economics, METU in 2014. I have been working as revenue management specialist in Turkish Airlines more than 4 years. I want to improve myself in a data analysis and this why I enroll this program.You can find my LinkedIn Profile [here](https://www.linkedin.com/)

**useR!2020: missMethods**

In this video, Tobias Rockel who is the creator of the package missMethods, talks about the package itself. Mainly, this package has three capabilities, which are creating the missing data, handling the mising data and evaluating the handling steps. The aim of the package is to maintain the reproducability. You can watch the video from the link below.

[YouTube Link](https://www.youtube.com/watch?v=G6JCXaPjG9g)

**Market Basket Analysis using R**

For a market, every transaction is a data. There can be similarities among people and products. We can search for it with some algorithms. You can see an example code for Apriori algorithm which is an Association Rule Mining algorithm.

[APRIORI Algorithm](https://www.datacamp.com/community/tutorials/market-basket-analysis-r)

**Introduction to Stock Analysis in R**

There are many stocks and for these stocks, there are many information about their values. We can make some analysis about the future behavior of these stocks. You can see an example analysis for stocks below.

[Stock Analysis](https://lamfo-unb.github.io/2017/07/22/intro-stock-analysis-1/)

**Sports Data Analysis and Visualization**

There are some data analysis in sports. I come up with the first analysis in Analytics Edge from Edx. It was fascinating to be able to understand the importance of analysis. With less money, we can be successful with the help of analysis. You can see an example of these analysis below.

[Sports Data Analysis and Visualization](http://mattwaite.github.io/sports/)
